import { Routes } from '@angular/router';
import { Welcome } from './pages/welcome/welcome';
import { Login } from './pages/login/login';
import { Register } from './pages/register/register';
import { Membercheck } from './pages/membercheck/membercheck';
import { ForgotPassword } from './pages/forgot-password/forgot-password';
import { Dashboard } from './pages/dashboard/dashboard';
import { GenerateQr } from './pages/generate-qr/generate-qr';
import { Notifications } from './pages/notifications/notifications';
import { ChangePassword } from './pages/change-password/change-password';
import { MemberProfile } from './pages/member-profile/member-profile';
import { Faqs } from './pages/faqs/faqs';
import { Terms } from './pages/terms/terms';
import { Privacy } from './pages/privacy/privacy';
import { Unsubscribe } from './pages/unsubscribe/unsubscribe';
import { MenuModal } from './pages/menu-modal/menu-modal';
import { EmailSent } from './pages/email-sent/email-sent';
import { Branches } from './pages/branches/branches';
import { UnsubscribeSuccess } from './pages/unsubscribe-success/unsubscribe-success';
import { CreateVoucher } from './pages/create-voucher/create-voucher';
import { Congratulations } from './pages/congratulations/congratulations';
import { EarnedPoints } from './pages/earned-points/earned-points';
import { UnusedVouchers } from './pages/unused-vouchers/unused-vouchers';
import { UsedVouchers } from './pages/used-vouchers/used-vouchers';

export const routes: Routes = [
  { path: '', redirectTo: 'welcome', pathMatch: 'full' },
  { path: 'welcome', component: Welcome },
  { path: 'login', component: Login },
  { path: 'register', component: Register },
  { path: 'privacy', component: Privacy },
  { path: 'membercheck', component: Membercheck },
  { path: 'forgot-password', component: ForgotPassword },
  { path: 'dashboard', component: Dashboard },
  { path: 'generate-qr', component: GenerateQr },
  { path: 'notifications', component: Notifications },
  { path: 'change-password', component: ChangePassword },
  { path: 'member-profile', component: MemberProfile },
  { path: 'faqs', component: Faqs },
  { path: 'terms', component: Terms },
  { path: 'unsubscribe', component: Unsubscribe },
  { path: 'menu-modal', component: MenuModal },
  { path: 'email-sent', component: EmailSent },
  { path: 'branches', component: Branches },
  { path: 'unsubscribe-success', component: UnsubscribeSuccess },
  { path: 'create-voucher', component: CreateVoucher },
  { path: 'congratulations', component: Congratulations },
  { path: 'earned-points', component: EarnedPoints },
  { path: 'unused-vouchers', component: UnusedVouchers },
  { path: 'used-vouchers', component: UsedVouchers }
];
